import commentsModel from "./comments-model.js";
export const findAllComments = () => commentsModel.find();
export const findCommentsByAuthorID = (authorID) => commentsModel.find({authorID: authorID});
export const findCommentsByPostID = (postID) => commentsModel.find({postID: postID});
export const findCommentsByContents = (text) => commentsModel.find({ text: { $regex: text, $options: "i" } });
export const findCommentsByTime = (start, end) => commentsModel.find({createdAt: {$gte: start, $lte: end}});
export const findCommentById = (cid) => commentsModel.findById(cid);
export const createComment = (comment) => commentsModel.create(comment);
export const deleteComment = (cid) => commentsModel.findByIdAndDelete(cid);
export const updateComment = (cid, comment) => commentsModel.findByIdAndUpdate(cid, { $set: comment });
